// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mobile/assignments/{assignmentId}/detail": {
            "get": {
                "description": "Returns all ends and arrow scores for a participant's qualification assignment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Scoring"
                ],
                "summary": "Get full score detail for an assignment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target assignment UUID",
                        "name": "assignmentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/auth/scorekeeper/login": {
            "post": {
                "description": "Login for scorekeepers using their unique code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Authentication"
                ],
                "summary": "Scorekeeper login",
                "parameters": [
                    {
                        "description": "Scorekeeper login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MobileScorekeeperLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MobileLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/elimination/scoring/matches/{matchId}/end": {
            "post": {
                "description": "Calculate winner from scores and finish the match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Elimination"
                ],
                "summary": "End match manually",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Winner details (optional)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handler.FinishMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/elimination/scoring/matches/{matchId}/finish": {
            "post": {
                "description": "Mark a match as finished and advance winner to next round",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Elimination"
                ],
                "summary": "Finish match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Winner details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.FinishMatchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/elimination/scoring/matches/{matchId}/reset": {
            "post": {
                "description": "Reset a finished match back to in_progress and remove winner from next round",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Elimination"
                ],
                "summary": "Reset match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/elimination/scoring/matches/{matchId}/score": {
            "post": {
                "description": "Update or create end scores for a match",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Elimination"
                ],
                "summary": "Update match score",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Match UUID",
                        "name": "matchId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Match score update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.MatchScoreRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/events": {
            "get": {
                "description": "Get events optimized for mobile view",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Events"
                ],
                "summary": "List mobile events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MobileEventsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/qualification/scoring/cards": {
            "get": {
                "description": "Get selectable target cards for scoring context",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Qualification",
                    "Mobile - Elimination"
                ],
                "summary": "Get scoring cards",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phase (qualification)",
                        "name": "phase",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category UUID",
                        "name": "category_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScoringCardsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/qualification/scoring/scores/{assignmentId}": {
            "post": {
                "description": "Update end scores for an assignment (supports batch)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Qualification"
                ],
                "summary": "Update qualification score",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Assignment UUID",
                        "name": "assignmentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Score update request (Standard Batch format)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ScoreBatchUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/qualification/scoring/targets": {
            "get": {
                "description": "Get scoring progress for a selected target in a session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Qualification"
                ],
                "summary": "Get scoring targets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Phase (qualification)",
                        "name": "phase",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Session UUID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Target Name (e.g. 1A)",
                        "name": "target_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ScoringTargetsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/scan": {
            "get": {
                "description": "Look up a target board by its barcode code and return archer list with scores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Scoring"
                ],
                "summary": "Scan target barcode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Barcode / QR code on the target board",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/mobile/sessions/boards": {
            "get": {
                "description": "Get all boards and their archers with score summaries for a qualification session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mobile - Scoring"
                ],
                "summary": "List all target boards in a session",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Qualification session UUID",
                        "name": "session_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.FinishMatchRequest": {
            "type": "object",
            "required": [
                "winner_entry_id"
            ],
            "properties": {
                "winner_entry_id": {
                    "type": "string"
                }
            }
        },
        "handler.MatchScoreRequest": {
            "type": "object",
            "required": [
                "end_no"
            ],
            "properties": {
                "arrows_a": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "arrows_b": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_no": {
                    "type": "integer"
                },
                "score_a": {
                    "type": "integer"
                },
                "score_b": {
                    "type": "integer"
                }
            }
        },
        "handler.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.MobileEvent": {
            "type": "object",
            "properties": {
                "banner_url": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "logo_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizer_avatar_url": {
                    "type": "string"
                },
                "organizer_name": {
                    "type": "string"
                },
                "participant_count": {
                    "type": "integer"
                },
                "start_date": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "handler.MobileEventsResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.MobileEvent"
                    }
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "handler.MobileLoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/handler.MobileUser"
                }
            }
        },
        "handler.MobileScorekeeperLoginRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "handler.MobileUser": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "handler.ScoringCard": {
            "type": "object",
            "properties": {
                "card_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "phase": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "session_name": {
                    "type": "string"
                },
                "session_order": {
                    "type": "integer"
                },
                "target_name": {
                    "type": "string"
                }
            }
        },
        "handler.ScoringCardsResponse": {
            "type": "object",
            "properties": {
                "cards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScoringCard"
                    }
                }
            }
        },
        "handler.ScoringTarget": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "participants": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "handler.ScoringTargetsResponse": {
            "type": "object",
            "properties": {
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ScoringTarget"
                    }
                }
            }
        },
        "models.ScoreBatchUpdateRequest": {
            "type": "object",
            "required": [
                "ends"
            ],
            "properties": {
                "ends": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SingleEndScore"
                    }
                }
            }
        },
        "models.SingleEndScore": {
            "type": "object",
            "required": [
                "arrows",
                "end_number"
            ],
            "properties": {
                "arrows": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "end_number": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "ArcheryHub Mobile API",
	Description:      "This documentation is exclusively for the ArcheryHub Mobile Application.\nNOTE: This Swagger only contains endpoints relevant to mobile app workflows (Scoring, Events, and Auth).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
